// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package api

type File struct {
	Name       *string `json:"name"`
	Usage      *int64  `json:"usage"`
	MountPoint *string `json:"mountPoint"`
}

type FileWhereInput struct {
	MountPoint string `json:"mountPoint"`
}
